[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

# Rule for api
[[redirects]]
  from = "/pocket/*"
  to = "https://getpocket.com/v3/:splat"
  status = 200
  force = true

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
