[build]
  command = "yarn build && yarn build:functions"
  publish = "dist"
  functions = ".netlify/functions"


# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200