[build]
  command = "yarn build"
  publish = "dist"

# Rule for api
[[redirects]]
  from = "/pocket/*"
  to = "https://getpocket.com/v3/:splat"
  status = 200
  force = true

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
